# generated by datamodel-codegen:
#   filename:  spec.yaml

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class CreateTransferRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    idempotencyKey: Annotated[
        str,
        Field(
            description="Client-supplied key. Required — see ADR-0002 for why this isn't optional.",
            min_length=1,
        ),
    ]
    fromWalletId: UUID
    toWalletId: UUID
    amount: Annotated[
        int,
        Field(
            description="Integer minor units (e.g. cents) — never a float. Deliberately unconstrained here (no minimum): non-positive amount is rejected as a domain-level invariant (ADR-0002), not a request-shape constraint, so it must reach the domain layer to be checked.\n"
        ),
    ]


class Status(Enum):
    """
    PENDING is never returned — see ADR-0008.
    """

    PROCESSED = "PROCESSED"
    FAILED = "FAILED"


class TransferResponse(BaseModel):
    id: UUID
    idempotencyKey: str
    fromWalletId: UUID
    toWalletId: UUID
    amount: int
    status: Annotated[Status, Field(description="PENDING is never returned — see ADR-0008.")]
    failureReason: Annotated[
        str | None,
        Field(
            description='Present when status is FAILED (e.g. "INSUFFICIENT_FUNDS"), null otherwise.'
        ),
    ] = None
    createdAt: datetime
    updatedAt: datetime


class ErrorResponse(BaseModel):
    detail: str
